apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-web
  labels:
    app: diary-web
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diary-web
  template:
    metadata:
      labels:
        app: diary-web
        component: frontend
    spec:
      containers:
      - name: web
        image: ghcr.io/your-username/diary/web:latest
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: PORT
          value: "3000"
        - name: API_URL
          value: "http://diary-api:3001"
        - name: NEXTAUTH_URL
          value: "https://diary.yourdomain.com"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: diary-secrets
              key: nextauth-secret
        - name: SESSION_TOKEN_COOKIE_NAME
          value: "authjs.session-token"
        - name: CSRF_TOKEN_COOKIE_NAME
          value: "authjs.csrf-token"
        - name: CALLBACK_URL_COOKIE_NAME
          value: "authjs.callback-url"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: diary-web
  labels:
    app: diary-web
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: diary-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diary-web
  labels:
    app: diary-web
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - diary.yourdomain.com
    secretName: diary-tls
  rules:
  - host: diary.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diary-web
            port:
              number: 3000